import { v4 as uuid } from "uuid";
import {
  img4,
  img5,
  img6,
  img7,
  img8,
  img9,
  img10,
  img11,
  img12,
  img13,
  img14,
  imgm1,
  imgm2,
  imgm3,
  imgm4,
  imgm5,
  imgm6,
  imgm7,
  imgm8,
  kids1,
  kids2,
  kids3,
  kids4,
  kids5,
  kids6,
  kids7,
  kids8,
} from "../../assests/image";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    imageUrl: img4,
    isLiked: false,
    rating: 4,
    title: "Women Western Top",
    price: "1000",
    categoryName: "women-cloth",
  },
  {
    _id: uuid(),
    imageUrl: kids1,
    isLiked: false,
    rating: 3,
    title: "Plain Woven Polyester Boat Nec",
    price: "700",
    categoryName: "kid-cloth",
  },
  {
    _id: uuid(),
    imageUrl: img7,
    isLiked: false,
    rating: 3,
    title: "Solid color top",
    price: "599",
    categoryName: "women-cloth",
  },
  {
    _id: uuid(),
    imageUrl: kids2,
    isLiked: false,
    rating: 4,
    title: "Solid Cotton Blend Flared",
    price: "949",
    categoryName: "kid-cloth",
  },
  {
    _id: uuid(),
    imageUrl: img8,
    isLiked: false,
    rating: 2,
    title: "Solid Georgette Square Neck",
    price: "599",
    categoryName: "women-cloth",
  },
  {
    _id: uuid(),
    imageUrl: img5,
    isLiked: false,
    rating: 4,
    title: "Men Black Shirt",
    price: "580",
    categoryName: "men-cloth",
  },
  {
    _id: uuid(),
    imageUrl: img6,
    isLiked: false,
    rating: 4,
    title: "Kid Dungaree Set",
    price: "1000",
    categoryName: "kid-cloth",
  },
  {
    _id: uuid(),
    imageUrl: img9,
    isLiked: false,
    rating: 3,
    title: "Floral Polyester Off Shoulder",
    price: "699",
    categoryName: "women-cloth",
  },
  {
    _id: uuid(),
    imageUrl: kids3,
    isLiked: false,
    rating: 2,
    title: "Printed Round Neck Girls",
    price: "649",
    categoryName: "kid-cloth",
  },
  {
    _id: uuid(),
    imageUrl: img14,
    isLiked: false,
    rating: 4,
    title: "Solid Polyester Mandarin",
    price: "519",
    categoryName: "women-cloth",
  },
  {
    _id: uuid(),
    imageUrl: kids4,
    isLiked: false,
    rating: 3,
    title: "Girls Solid Round Neck",
    price: "450",
    categoryName: "kid-cloth",
  },
  {
    _id: uuid(),
    imageUrl: imgm1,
    isLiked: false,
    rating: 3,
    title: "Checks Cotton Slim Fit ",
    price: "550",
    categoryName: "men-cloth",
  },
  {
    _id: uuid(),
    imageUrl: kids5,
    isLiked: false,
    rating: 4,
    title: "Printed Lurex & Georgette Printed top",
    price: "701",
    categoryName: "kid-cloth",
  },
  {
    _id: uuid(),
    imageUrl: imgm2,
    isLiked: false,
    rating: 3,
    title: "Solid Linen Cotton I-Fit ",
    price: "800",
    categoryName: "men-cloth",
  },
  {
    _id: uuid(),
    imageUrl: kids6,
    isLiked: false,
    rating: 4,
    title: "Solid Polyester Collared Girls",
    price: "600",
    categoryName: "kid-cloth",
  },
  {
    _id: uuid(),
    imageUrl: imgm3,
    isLiked: false,
    rating: 3,
    title: "Solid Linen Cotton I-Fit ",
    price: "820",
    categoryName: "men-cloth",
  },
  {
    _id: uuid(),
    imageUrl: img10,
    isLiked: false,
    rating: 4,
    title: "Checks Cotton Boat Neck",
    price: "850",
    categoryName: "women-cloth",
  },
  {
    _id: uuid(),
    imageUrl: kids7,
    isLiked: false,
    rating: 4,
    title: "Girls Regular Fit Collared Printed ",
    price: "600",
    categoryName: "kid-cloth",
  },
  {
    _id: uuid(),
    imageUrl: imgm4,
    isLiked: false,
    rating: 3,
    title: "Printed Cotton Regular Fit",
    price: "650",
    categoryName: "men-cloth",
  },
  {
    _id: uuid(),
    imageUrl: kids8,
    isLiked: false,
    rating: 2,
    title: "Girls Square Neck Embroidered",
    price: "500",
    categoryName: "kid-cloth",
  },
  {
    _id: uuid(),
    imageUrl: img11,
    isLiked: false,
    rating: 4,
    title: "Solid Georgette Round Neck",
    price: "650",
    categoryName: "women-cloth",
  },
  {
    _id: uuid(),
    imageUrl: imgm5,
    isLiked: false,
    rating: 3,
    title: "Printed Cotton Slim Fit",
    price: "890",
    categoryName: "men-cloth",
  },
  {
    _id: uuid(),
    imageUrl: img12,
    isLiked: false,
    rating: 2,
    title: "Solid Viscose V-Neck ",
    price: "499",
    categoryName: "women-cloth",
  },
  {
    _id: uuid(),
    imageUrl: imgm6,
    isLiked: false,
    rating: 4,
    title: " Solid Linen Blend Slim Fit ",
    price: "660",
    categoryName: "men-cloth",
  },
  {
    _id: uuid(),
    imageUrl: img13,
    isLiked: false,
    rating: 2,
    title: "Solid Viscose V-Neck ",
    price: "499",
    categoryName: "women-cloth",
  },
  {
    _id: uuid(),
    imageUrl: imgm7,
    isLiked: false,
    rating: 2,
    title: "Checks Cotton Regular Fit",
    price: "840",
    categoryName: "men-cloth",
  },
  {
    _id: uuid(),
    imageUrl: imgm8,
    isLiked: false,
    rating: 3,
    title: "Solid Linen Cotton I-Fit",
    price: "770",
    categoryName: "men-cloth",
  },
];
